### ISSUE TITLE
Prepare data for wastewater materials

### ISSUE THREAD

**Issue by tavareshugo** [cambiotraining/sars-cov-2-genomics#43]
We have a subset of 60 samples from [Karthikeyan et al.](https://doi.org/10.1038/s41586-022-05049-6) that show a transition between delta and omicron variants. 

To run it live in a workshop we need to have the pipeline finish in under 1h. 
If that is not possible, we may need to instead use a `preprocessed` folder with results from 60 samples and in the workshop they only process 5-10 samples. 

- [ ] test how long it takes to run 60 or 30 samples. 
- [ ] prepare participant data directories with the files needed for the workshop. This includes:
  - `data/reads` - FASTQ files
  - `scripts` - shell scripts that they will fix in the exercises
  - `utilities` - python scripts we provide, e.g. to prepare samplesheet or tidy freyja output files
  - `sample_info.csv` metadata table with "sample,date,country,location,latitude,longitude"

**Comment by tavareshugo** [comment]
Command to run pipeline: 

```bash
nextflow run nf-core/viralrecon \
  -profile singularity  -r dev  \
  --max_memory '16.GB' --max_cpus 8 \
  --fastq_dir "data/reads" \
  --input samplesheet.csv \
  --genome 'MN908947.3' \
  --platform illumina \
  --protocol amplicon \
  --primer_set artic \
  --primer_set_version 4.1 \
  --outdir results/viralrecon \
  --variant_caller ivar \
  --consensus_caller ivar \
  --skip_picard_metrics \
  --skip_asciigenome \
  --skip_assembly
```

**Comment by bsalehe** [comment]
Hi @tavareshugo, It took me 2h 11m 9s to run 3 samples on Ubuntu. So 5 samples may take minimum "4hrs". I think we may end up only using preprocessed results instead???

![viralrecon_run_screenshot](https://github.com/cambiotraining/sars-cov-2-genomics/assets/3806040/bb1565c0-f610-4b06-a7ad-3e607f6bf1b0)

**Comment by tavareshugo** [comment]
Bajuna tested running 3 samples with `--freyja_boot 1` and it ran in 50 minutes - this is a good alternative to run in the workshop. 

`--freyja_boot 0` throws an error.

**Comment by bsalehe** [comment]
For training purpose we may instruct participants to download BED file [here](https://github.com/ucsd-ccbb/C-VIEW/blob/main/reference_files/sarscov2_v2_primers.bed) for SWIFT_V2 which was used for pipeline datasets as the codes show [here](https://github.com/ucsd-ccbb/C-VIEW/blob/8d2e9f75790222907291b42442d2b83d4ec53728/pipeline/run_cview.sh#L92C6-L93C51)

**Comment by bsalehe** [comment]
I consistently get this error:-

```
Command error:
  Traceback (most recent call last):
    File "/home/bajuna/.nextflow/assets/nf-core/viralrecon/bin/collapse_primer_bed.py", line 86, in <module>
      sys.exit(main())
    File "/home/bajuna/.nextflow/assets/nf-core/viralrecon/bin/collapse_primer_bed.py", line 82, in main
      collapse_primer_bed(args.FILE_IN, args.FILE_OUT, args.LEFT_PRIMER_SUFFIX, args.RIGHT_PRIMER_SUFFIX)
    File "/home/bajuna/.nextflow/assets/nf-core/viralrecon/bin/collapse_primer_bed.py", line 58, in collapse_primer_bed
      chrom, start, end, name, score, strand = line.strip().split("\t")
  ValueError: not enough values to unpack (expected 6, got 4)

Work dir:
  /home/bajuna/wastewater_surveillance/work/68/2c5eed79b029de1fa0c8e8530cf35b

``` 

I think the bed file even when trying to convert to BED6 as instructed [here](https://nf-co.re/viralrecon/2.6.0/docs/usage#swift-primer-sets) it is still missing one column apparently two strands columns as in artic bed file. I have found this swift_v2_masterfile [here](https://github.com/greninger-lab/covid_swift_pipeline/blob/master/masterfiles/sarscov2_swift_v2_masterfile.txt). So, I wonder if we need to extract the left and right primer sequences to the swift bed file hopefully to avoid this error????

Cheers!

**Comment by bsalehe** [comment]
Now with SWIFT provided bed file which was converted to bed6 with this one liner `cat sarscov2_v2_primers.bed | perl -lane 'if (/F/) {print $F[0]\t$F[1]\t$F[2]\t$F[3]\t0\t+} else {print $F[0]\t$F[1]\t$F[2]\t$F[3]\t0\t-}' > swift_primers.bed`, the pipeline ran successfully approximately 51 minutes using 3 samples. The full viralrecon code used is:

```
nextflow run nf-core/viralrecon \
  -profile singularity  -r dev \
  --max_memory '16.GB' --max_cpus 8 \
  --fastq_dir "reads" \
  --input samplesheet.csv \
  --genome 'NC_045512.2' \
  --fasta resources/NC_045512.2.fa \
  --gff resources/NC_045512.2.gff \
  --platform illumina \
  --protocol amplicon \
  --primer_bed resources/swift_primers.bed \
  --ivar_trim_offset 5 \
  --primer_left_suffix '_F' \
  --primer_right_suffix '_R' \
  --outdir results/viralrecon \
  --variant_caller ivar \
  --consensus_caller ivar \
  --skip_picard_metrics \
  --skip_asciigenome \
  --skip_assembly \
  --skip_nextclade \
  --skip_pangolin \
  --freyja_repeats 1
```

Should we start now preparing learning objectives for the sars-cov2-genomics wastewater surveillance [section](https://cambiotraining.github.io/sars-cov-2-genomics/materials/04-wastewater/01-wastewater_surveillance.html)?
